export default {
    CHANGE_VIEW: "CHANGE_VIEW",
    REQUEST_ALL_EVENTS: "REQUEST_ALL_EVENTS",
    REQUEST_ALL_EVENTS_SUCCEEDED: "REQUEST_ALL_EVENTS_SUCCEEDED",
    REQUEST_ALL_EVENTS_ERROR: "REQUEST_ALL_EVENTS_ERROR",
    CHANGE_FILTER: "CHANGE_FILTER",
    SAVE_EVENT: "SAVE_EVENT",
    EVENT_SAVED: "EVENT_SAVED",
    EVENT_SAVE_ERROR: "EVENT_SAVE_ERROR",
    EVENT_CLEAR: "EVENT_CLEAR"
};
