export default {
    CHANGE_VIEW: "CHANGE_VIEW",
    REQUEST_ALL_EVENTS: "REQUEST_ALL_EVENTS",
    REQUEST_ALL_EVENTS_SUCCEEDED: "REQUEST_ALL_EVENTS_SUCCEEDED",
    REQUEST_ALL_EVENTS_ERROR: "REQUEST_ALL_EVENTS_ERROR",
    CHANGE_FILTER: "CHANGE_FILTER"
};
