export default {
    REQUEST_LOGIN: "REQUEST_LOGIN",
    AUTH_SUCCESS: "AUTH_SUCCESS",
    AUTH_FAIL: "AUTH_FAIL",
    VERIFY_AUTH: "VERIFY_AUTH",
    VERIFY_AUTH_SUCCESS: "VERIFY_AUTH_SUCCESS",
    VERIFY_AUTH_FAIL: "VERIFY_AUTH_FAIL",
    LOGOUT: "LOGOUT"
};
